name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: node:16
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # gives semantic-release access to all previous commits
          token: ${{ secrets.GH_TOKEN }} # admin token
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ env.cache-name }}-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn
      - name: Cut release
        id: cut_release
        # run: yarn release
        run: |
          yarn release
          echo "Event release tag"
          echo ${{ github.event.release.tag_name }}
      - name: Get the tag name
        id: get_tag_version
        run: |
          yarn version -v
          echo "TAG_VERSION=$(npm pkg get version)" >> $GITHUB_ENV
      - name: Get current version
        run: |
          echo 'v${{ env.TAG_VERSION }}'
          echo "steps.get_tag_version.outputs"
          echo ${{ toJSON(steps.get_tag_version.outputs) }}
          echo "steps.cut_release.outputs"
          echo ${{ toJSON(steps.cut_release.outputs) }}
          echo ${{ github.event.release.tag_name }}
          echo ${{ github.ref }}
      